services:
  minio:
    image: quay.io/minio/minio:latest
    hostname: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${SECRET_KEY}
    volumes:
      - ./minio/data:/data
    command: server --console-address ":9001" /data
